### ISSUE TITLE
REST API to create diagnostic settings

### ISSUE THREAD

**Issue by khaliddermoumi** [mattfeltonma/Collect-ManagementGroupActivityLogs#1]
Hi!
Thanks for your work, there is a REST API to create diagnostic settings since a while:
https://docs.microsoft.com/en-us/rest/api/monitor/management-group-diagnostic-settings/create-or-update
I tried deploying a diagnostic setting using bicep, this did work too.
Would make sense if you mention this in the README, imho.

**Comment by mattfeltonma** [comment]
Great suggestion. I will do that!
